- name: Create local bin directory
  file:
    path: "{{ ansible_user_dir }}/.local/bin"
    state: directory

- name: Set authorized_keys
  ansible.posix.authorized_key:
    user: jhood
    state: present
    key: "{{ lookup('file', 'jhood_key.pub') }}"
    exclusive: true

- name: Install Shell Tools
  apt:
    name:
      - git
      - unzip
      - jq
      - silversearcher-ag
      - tree
      - htop
      - curl
    state: present
  become: true

- name: Configure git email
  community.general.git_config:
    name: user.email
    value: jonathan@thehoods.io
    scope: global

- name: Configure git username
  community.general.git_config:
    name: user.name
    value: Jonathan Hood
    scope: global
